### PR TITLE
Bump nodejs stable and unstable versions to latest

### PR DESCRIPTION
**Pull request by sandfox**

### CODE REVIEW

**Comment by michaelklishin** [comment]
This project is no longer used.

**Comment by gildegoma** [comment]
@michaelklishin good to know, but where and how are now the final runlists defined ?

**Comment by michaelklishin** [comment]
I believe in [travis-images](https://github.com/travis-ci/travis-images), @joshk can confirm :)

**Comment by gildegoma** [comment]
OK, thanks @michaelklishin for the link (I didn't read the repo list well enough, sincerely sorry).

@sandfox In continuation to travis-ci/travis-cookbooks#214, I think we'd care to also update https://github.com/travis-ci/travis-images/blob/master/templates/worker.node-js.yml#L16. See also travis-ci/travis-cookbooks#197 and travis-ci/travis-boxes#17 that aim to simplify such kind of maintenance tasks...

**Comment by sandfox** [comment]
@gildegoma thanks, I'll have look and make the relevant updates, and have a dig through those other tickets.

@michaelklishin Is it worth sticking a little note on the front of the repo stating it's depreciated (for the benefit of others)? Am happy to make a PR for it, or add it to this one if we're feeling lazy

**Comment by joshk** [comment]
I updated the readme to note that this repo is not currently maintained. I will blog out our tooling soon.

Thanks for the PR none the less, High 5!

**Pull request closed without merging**
