### PR TITLE
Add alias for node-head

### PR DESCRIPTION
**Pull request by nschonni**
Fixes https://github.com/travis-ci/travis-ci/issues/1017

### CODE REVIEW

**Comment by sarahhodne** [comment]
We probably want this change in travis-build instead, see how [Rubinius aliases](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/rvm.rb#L23-28) are made.

**Comment by nschonni** [comment]
Maybe, I was following the basic pattern from https://github.com/travis-ci/travis-boxes/commit/69689a1eb3fb76ef8e02d5f6becdb31f42e532d2, but maybe something more dynamic would be a good idea. Head is really use the latest odd number release with node and not a separate binary release Travis is building.

**Comment by sarahhodne** [comment]
@joshk WDYT?

**Comment by joshk** [comment]
I think we should move this to travis-build and instead of using `node-head` we can just use `head`. The reason being is that instead of pinning `head` to an exact version, it should just point to a major version (as the minor is more likely to update often).

**Comment by nschonni** [comment]
Ok

**Pull request closed without merging**
