### PR TITLE
Bump Veewee box to Ubuntu Precise 12.04.1 LTS (Precise)

### PR DESCRIPTION
**Pull request by runlevel5**
Well, the image that is used on Travis and Travis Pro are precise32, so I guess it is okay for me to submit this pull request to bump the definition of veewee from oneiric to precise unless there are reasons not to.

### CODE REVIEW

**Comment by runlevel5** [comment]
Obviously now, I need to upload the precise32_base_v2.box to files.travis-ci.org first. I'll ping @michaelklishin to do it for me or get my SSH key in so I could upload.

**Comment by michaelklishin** [comment]
That's not how it works. There is a separate repo with definitions of various distros. `precise32_base_v2` is an image built from the 12.04 definition. It should already be at 12.04.1 and has been for a couple of months or more.

**Comment by michaelklishin** [comment]
The repo is at https://github.com/travis-ci/veewee-definitions

**Comment by joshk** [comment]
I'll be honest, I didn't even know we were using this repo.

We need to remove veewee from travis-boxes, as well as the definition that is in there

**Comment by michaelklishin** [comment]
Done in 3d88dc3d27c728e3145d2e073efb5b000e313042

**Pull request closed without merging**
