### PR TITLE
Updating to the latest node releases

### PR DESCRIPTION
**Pull request by davglass**
Just updating to the latest nodejs version :)

Thanks!

### CODE REVIEW

**Comment by joshk** [comment]
Hey @davglass, sorry but this repo is no longer used for VM creation, I now use travis-images.

Huge High 5 and :heart:

**Comment by davglass** [comment]
Cool, when I get to a machine I'll file a request for that repo then :)

**Comment by joshk** [comment]
You rock!

**Comment by davglass** [comment]
Looks like it's already up to date:
https://github.com/travis-ci/travis-images/blob/master/templates/worker.node-js.yml

When are these scheduled to be updated so I can turn my Node 0.11.x tests
back on?

**Comment by joshk** [comment]
I am hoping for 2 weeks, I just need to do some test provisioning and testing first.

**Comment by davglass** [comment]
Sweet, thanks! I'll keep an eye out for the update then..

**Pull request closed without merging**
